"""Delete unused fields

Revision ID: 508d5a3cf8af
Revises: 95b0f927bd63
Create Date: 2024-05-30 22:27:29.286254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508d5a3cf8af'
down_revision: Union[str, None] = '95b0f927bd63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
